export const ATTEMPT_LOGIN = 'ATTEMPT_LOGIN';
export const ATTEMPT_LOGOUT = 'ATTEMPT_LOGOUT';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const FETCH_COMPLAINTS = 'FETCH_COMPLAINTS';
export const COMPLAINTS_FETCHED = 'COMPLAINTS_FETCHED';
export const COMPLAINTS_FETCH_ERROR = 'COMPLAINTS_FETCH_ERROR';
export const CLEAR_COMPLAINTS = 'CLEAR_COMPLAINTS';
